services:
  app:
    build:
      context: .
    ports:
      - "8080:8080"
    environment:
      - APP_ENV=${APP_ENV}
      - DB_USER=${DB_USER}
      - DB_PASSWORD=${DB_PASSWORD}
      - DB_DOMAIN=${DB_DOMAIN}
      - DB_NAME=${DB_NAME}
      - CLIENT_SECRET=${CLIENT_SECRET}
      - ENABLE_DB_LOGGER=${ENABLE_DB_LOGGER}
      - LOG_LEVEL=${LOG_LEVEL}
      - ENABLE_RATE_LIMIT=${ENABLE_RATE_LIMIT}
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
