### Create ticket
POST http://localhost:3005/kanban/v1/tickets HTTP/1.1
Content-Type: application/json
Authorization: Bearer <access token>

{
    "title": "new ticket created by test user",
    "description": "this is the ticket created by test user",
    "assignees": ["frontend", "backend", "design"],
    "status": "todo"
}

### Get all tickets
GET http://localhost:3005/kanban/v1/tickets
Content-Type: application/json
Accept: application/json
Authorization: Bearer <access token>


### Update ticket
PUT http://localhost:3005/kanban/v1/tickets/0d3aa27533bc4b1e982398f2d0ec2bf2
Content-Type: application/json
Authorization: Bearer <access token>

{
    "title": "Updated ticket by jane doe",
    "description": "this is the ticket created by jane doe",
    "assignees": ["frontend", "design"],
    "status": "todo"
}

### Delete ticket
DELETE http://localhost:3005/kanban/v1/tickets/0d3aa27533bc4b1e982398f2d0ec2bf2
Content-Type: application/json
Authorization: Bearer <access token>
